### ISSUE TITLE
Find out which image is missing

### ISSUE THREAD

**Issue by xavez** [mono-company/bedrock#146]
It sometimes happens to me that I get the following error when starting a project with the `gulp` command:

```
Error: Cannot find module 'png'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at new View (/Users/me/desktop-prototype/node_modules/express/lib/view.js:78:30)
    at Function.render (/Users/me/desktop-prototype/node_modules/express/lib/application.js:569:12)
    at renderView (/Users/me/desktop-prototype/core/tasks/server.js:35:9)
    at /Users/me/desktop-prototype/core/tasks/server.js:86:5
    at Layer.handle [as handle_request] (/Users/me/desktop-prototype/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/me/desktop-prototype/node_modules/express/lib/router/route.js:131:13)
```

I know that this means some image is missing, but it’s not always clear which image is missing. Is there a way to provide a more descriptive error log? Such as which template triggers the error?

**Comment by thomastuts** [comment]
The vague 'Cannot find module' errors have been fixed, and instead you get a nicely formatted error message showing you what file is missing, and where it was requested from:

![image](https://cloud.githubusercontent.com/assets/1914255/23659096/528638c2-0345-11e7-8f86-5cb565755a81.png)

**Comment by Wolfr** [comment]
Super great!
