### ISSUE TITLE
node 0.12 warning

### ISSUE THREAD

**Issue by Wolfr** [mono-company/bedrock#80]
If you use node 0.12 and try to run the prototype, you get this error:

    ^^^^^
    SyntaxError: Use of const in strict mode.
        at exports.runInThisContext (vm.js:73:16)
        at Module._compile (module.js:443:25)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
        at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:179:16)
        at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)

is there some way we can warn people if they use node 0.12?

**Comment by Dietr** [comment]
You can add a `.nvmrc` file which specifies the node version and lets you switch to the correct version when you are using multiple node versions. More info on https://github.com/creationix/nvm
