### ISSUE TITLE
Use of const in strict mode.

### ISSUE THREAD

**Issue by driesderoeck** [mono-company/bedrock#88]
After cloning and running npm install, I get following error:
```/bedrock/gulpfile.js:3
const gulp = require('gulp');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)```

**Comment by Wolfr** [comment]
Which version of node are you using?

`node -v`

**Comment by driesderoeck** [comment]
Updated to v5.4.1 - seems to be running fine now.

**Comment by Wolfr** [comment]
I am running node 4.2.1, didn't know there was a 5 already too.

https://nodejs.org/en/

I use nvm to be able to run multiple versions of node.

**Comment by Wolfr** [comment]
So you set everything up using `brew` and without using sudo?

**Comment by driesderoeck** [comment]
I set everything up using brew. My brew / user setup is similar to this one : http://blog.strug.de/2012/06/my-homebrew-multi-user-setup/
